[package]
name = "keybee"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
serde = { version = "1.0.132", features = ["derive"] }
parking_lot = "0.11.2"

winit = { version = "0.25.0", optional = true }
gilrs = { version = "0.8.1", optional = true }
